### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by tafxle** [Kajiya-aru/AniTorrent#2]
~/compile/AniTorrent/Anitorrent # python3 main.py               
Traceback (most recent call last):
  File "/home/artemiy/compile/AniTorrent/Anitorrent/main.py", line 285, in <module>
    launch()
  File "/home/artemiy/compile/AniTorrent/Anitorrent/main.py", line 280, in launch
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/home/artemiy/compile/AniTorrent/Anitorrent/main.py", line 19, in __init__
    self.setup()
  File "/home/artemiy/compile/AniTorrent/Anitorrent/main.py", line 38, in setup
    self.ui_init()
  File "/home/artemiy/compile/AniTorrent/Anitorrent/ui/gui.py", line 23, in ui_init
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
    ^^^^^^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by a-hr** [comment]
those dependencies have been removed, it should be working now
